[package]
name = "ckb-shared"
version = "0.12.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
ckb-core = { path = "../core" }
ckb-chain-spec = { path = "../spec" }
ckb-util = { path = "../util" }
ckb-store = { path = "../store" }
ckb-db = { path = "../db" }
jsonrpc-types = { path = "../util/jsonrpc-types" }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "b36a4d1" }
faketime = "0.2"
log = "0.4"
ckb-traits = { path = "../traits" }
failure = "0.1.5"
ckb-verification = { path = "../verification" }
ckb-protocol = { path = "../protocol" }
flatbuffers = "0.5.0"
ckb-script = { path = "../script" }

[dev-dependencies]
env_logger = "0.6"
tempfile = "3.0"
rand = "0.6"
serde_json = "1.0"
