name = "ckb_dev"

[genesis]
version = 0
parent_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
timestamp = 0
difficulty = "0x100"
uncles_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
# run `cargo run cli hashes -b` to get the genesis hash
hash = "0x22fdc49ddbae1b3c9658121363cb26dc8faeb89424b176df16fc59e8b8de57eb"
issued_cells = []

[genesis.seal]
nonce = 0
proof = [0]

[genesis.genesis_cell]
message = ""

[genesis.genesis_cell.lock]
code_hash = "0xb35557e7e9854206f7bc13e3c3a7fa4cf8892c84a09237fb0aab40aab3771eee"
args = []

# An array list paths to system cell files, which is absolute or relative to
# the directory containing this config file.
[genesis.system_cells]
files = []

[genesis.system_cells.lock]
code_hash = "0xb35557e7e9854206f7bc13e3c3a7fa4cf8892c84a09237fb0aab40aab3771eee"
args = []

[params]
epoch_reward = 5_000_000_000_000_000
secondary_epoch_reward = 5_000_000_000
max_block_cycles = 10_000_000_000
cellbase_maturity = 0

[pow]
func = "Cuckoo"

[pow.params]
# the 2-log of the graph size, which is the size in bits of the node
# identifiers
edge_bits = 15

# length of the cycle to be found, must be an even number, a minimum of 12 is
# recommended
cycle_length = 12
